// Cross-checked against real base64.b32encode(...) output from Python (the same
// function core/hashing.py uses) -- fixtures.json's `base32` array was generated by
// running the real Python function, not hand-computed.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { base32Encode } from '../base32.js';

const fixtures = JSON.parse(
  readFileSync(fileURLToPath(new URL('./fixtures.json', import.meta.url)), 'utf8'),
);

test('base32Encode matches Python base64.b32encode for known vectors', () => {
  for (const { input_b64, expected_b32 } of fixtures.base32) {
    const bytes = Uint8Array.from(Buffer.from(input_b64, 'base64'));
    assert.equal(base32Encode(bytes), expected_b32, `input_b64=${input_b64}`);
  }
});

test('base32Encode output length is always a multiple of 8 (padding)', () => {
  for (let len = 0; len <= 16; len++) {
    const bytes = new Uint8Array(len).fill(0xab);
    assert.equal(base32Encode(bytes).length % 8, 0, `len=${len}`);
  }
});

test('base32Encode of empty input is empty string', () => {
  assert.equal(base32Encode(new Uint8Array(0)), '');
});
